"""
Secure email delivery module using smtplib.
All SMTP credentials are read strictly from environment variables.
"""
import os
import re
import smtplib
import textwrap
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.utils import formatdate, make_msgid

from security.sanitizer import get_secure_logger

logger = get_secure_logger(__name__)

_EMAIL_RE = re.compile(
    r'^[a-zA-Z0-9]'
    r'[a-zA-Z0-9._%+\-]{0,62}'
    r'@'
    r'[a-zA-Z0-9\-]{1,63}'
    r'(?:\.[a-zA-Z0-9\-]{1,63})*'
    r'\.[a-zA-Z]{2,10}$'
)
_HEADER_INJECT_RE = re.compile(r'[\r\n\t\x00]')


def validate_email_address(address: str) -> str:
    """
    Validate and sanitize an email address.

    Raises ValueError if:
      - address is empty or too long
      - contains header-injection characters (CR, LF, tab, NUL)
      - does not match the strict RFC-5321 pattern
    Returns the lowercase-stripped address on success.
    """
    if not isinstance(address, str):
        raise ValueError("Email address must be a string.")

    address = address.strip()

    if not address:
        raise ValueError("Recipient email address is required.")

    if len(address) > 254:
        raise ValueError("Email address exceeds maximum length of 254 characters.")

    if _HEADER_INJECT_RE.search(address):
        raise ValueError("Email address contains illegal characters (possible injection attempt).")

    if not _EMAIL_RE.fullmatch(address):
        raise ValueError(f"'{address}' is not a valid email address.")

    return address.lower()


def _smtp_settings() -> dict:
    """Read and validate SMTP settings from environment variables."""
    server = os.getenv("SMTP_SERVER", "").strip()
    port_str = os.getenv("SMTP_PORT", "587").strip()
    sender = os.getenv("SENDER_EMAIL", "").strip()
    password = os.getenv("SENDER_PASSWORD", "").strip()

    missing = []
    if not server:
        missing.append("SMTP_SERVER")
    if not sender:
        missing.append("SENDER_EMAIL")
    if not password:
        missing.append("SENDER_PASSWORD")
    if missing:
        raise EnvironmentError(
            f"Missing required SMTP environment variables: {', '.join(missing)}"
        )

    try:
        port = int(port_str)
        if port < 1 or port > 65535:
            raise ValueError
    except ValueError:
        raise ValueError(f"SMTP_PORT must be a valid port number (1–65535), got: {port_str!r}")

    return {"server": server, "port": port, "sender": sender, "password": password}


def is_smtp_configured() -> bool:
    """Return True if all required SMTP env vars are set (non-empty)."""
    return all(
        os.getenv(k, "").strip()
        for k in ("SMTP_SERVER", "SENDER_EMAIL", "SENDER_PASSWORD")
    )


def send_proposal_email(
    recipient: str,
    job_title: str,
    company: str,
    proposal_text: str,
) -> tuple[bool, str | None]:
    """
    Send a proposal via SMTP (STARTTLS on port 587, SSL on port 465).

    Returns (True, None) on success, (False, error_message) on failure.
    The recipient address is validated before any SMTP connection is made.
    """
    try:
        recipient = validate_email_address(recipient)
    except ValueError as exc:
        return False, str(exc)

    try:
        cfg = _smtp_settings()
    except (EnvironmentError, ValueError) as exc:
        logger.error(f"SMTP configuration error: {exc}")
        return False, str(exc)

    subject = f"Proposal: {job_title} @ {company}"

    plain_body = textwrap.dedent(f"""\
        Hello,

        Please find below a tailored proposal for the position:

        Job Title : {job_title}
        Company   : {company}

        ─────────────────────────────────────────
        {proposal_text}
        ─────────────────────────────────────────

        This proposal was generated by CrewAI Job Agent and reviewed by a human operator.

        Regards,
        CrewAI Job Agent
    """)

    html_body = f"""\
<html><body style="font-family:sans-serif;color:#222;max-width:680px;margin:auto;padding:20px">
  <h2 style="color:#5865f2">Proposal: {_esc(job_title)}</h2>
  <p><strong>Company:</strong> {_esc(company)}</p>
  <hr style="border:none;border-top:1px solid #ddd"/>
  <div style="white-space:pre-wrap;background:#f9f9f9;padding:16px;border-radius:6px;font-size:15px">
    {_esc(proposal_text)}
  </div>
  <hr style="border:none;border-top:1px solid #ddd"/>
  <p style="color:#888;font-size:12px">Sent by CrewAI Job Agent · Human-reviewed proposal</p>
</body></html>"""

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = cfg["sender"]
    msg["To"] = recipient
    msg["Date"] = formatdate(localtime=False)
    msg["Message-ID"] = make_msgid(domain=cfg["sender"].split("@")[-1])
    msg.attach(MIMEText(plain_body, "plain", "utf-8"))
    msg.attach(MIMEText(html_body, "html", "utf-8"))

    try:
        if cfg["port"] == 465:
            with smtplib.SMTP_SSL(cfg["server"], cfg["port"], timeout=15) as smtp:
                smtp.login(cfg["sender"], cfg["password"])
                smtp.sendmail(cfg["sender"], recipient, msg.as_string())
        else:
            with smtplib.SMTP(cfg["server"], cfg["port"], timeout=15) as smtp:
                smtp.ehlo()
                smtp.starttls()
                smtp.ehlo()
                smtp.login(cfg["sender"], cfg["password"])
                smtp.sendmail(cfg["sender"], recipient, msg.as_string())

        logger.info(f"Proposal email sent to {recipient} for job: {job_title}")
        return True, None

    except smtplib.SMTPAuthenticationError:
        logger.error("SMTP authentication failed — check SENDER_EMAIL / SENDER_PASSWORD.")
        return False, "SMTP authentication failed. Check your sender credentials."
    except smtplib.SMTPConnectError:
        logger.error(f"Cannot connect to SMTP server {cfg['server']}:{cfg['port']}")
        return False, f"Could not connect to SMTP server ({cfg['server']}:{cfg['port']})."
    except smtplib.SMTPRecipientsRefused:
        logger.warning(f"SMTP server refused recipient: {recipient}")
        return False, f"Recipient address was refused by the mail server."
    except smtplib.SMTPException as exc:
        logger.error(f"SMTP error: {exc}")
        return False, f"Mail delivery failed: {exc}"
    except OSError as exc:
        logger.error(f"Network error sending email: {exc}")
        return False, f"Network error: {exc}"


def _esc(text: str) -> str:
    """HTML-escape text for use inside the email body."""
    return (
        str(text)
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
        .replace("'", "&#x27;")
    )
